=== szkarosisz1/DLWGQZ_XMLGyak/XMLTaskDLWGQZ/XMLSchemaDLWGQZ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--Egyszerű típusok kigyűjtése-->
    <!--Csapat-->
    <xs:element name="Vezetőedző" type="xs:string" />
    <xs:element name="Név" type="xs:string" />
    <!--Logó-->
    <xs:element name="Színek" type="xs:string" />
    <xs:element name="Tervező" type="xs:string" />
    <!--Csoport-->
    <xs:element name="Jelölés" type="jelolesTipus" />
    <!--Labdarúgó-->
    <xs:element name="Poszt" type="xs:string" />
    <xs:element name="Keresztnév" type="xs:string" />
    <xs:element name="Vezetéknév" type="xs:string" />
    <xs:element name="Gól" type="golTipus" />
    <xs:element name="Mezszám" type="xs:int" />
    <xs:element name="Szülidő" type="datumTipus" />
    <!--Mérkőzés-->
    <xs:element name="Csapat1Gólok" type="golTipus" />
    <xs:element name="Csapat2Gólok" type="golTipus" />
    <!--Helyszín-->
    <xs:element name="Férőhely" type="ferohelyTipus" />
    <xs:element name="Tulajdonos" type="xs:string" />    
    <xs:element name="Város" type="xs:string"/>  
    <!--Mérkőzik-->
    <xs:element name="Dátum" type="datumTipus" />
    <!--Saját típusok meghatározása-->
    <xs:simpleType name="jelolesTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D" />
            <xs:enumeration value="E" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ferohelyTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="30000" />
            <xs:maxInclusive value="100000" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="golTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="10" />
    </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="datumTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>    
    <!--Komplex típusokhoz saját típus meghatározása-->
    <xs:complexType name="csapatTípus">
        <xs:sequence>        
            <xs:element ref="Vezetőedző" />
            <xs:element ref="Név" />
        </xs:sequence>
            <xs:attribute name="CSkód" type="xs:integer" use="required" />
            <xs:attribute name="Csapatkapitány" type="xs:string" />
            <xs:attribute name="CSOPkód" type="xs:integer" />
            <xs:attribute name="LOGÓkód" type="xs:integer" />
    </xs:complexType>    
    <xs:complexType name="logóTípus">
        <xs:sequence>          
            <xs:element ref="Színek" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="Tervező" />
        </xs:sequence>
            <xs:attribute name="LOGÓkód" type="xs:integer" use="required" />
    </xs:complexType>         
    <xs:complexType name="csoportTípus">        
        <xs:sequence>
            <xs:element ref="Jelölés" />
        </xs:sequence>
                <xs:attribute name="CSOPkód" type="xs:integer" use="required" />
    </xs:complexType>   
    <xs:complexType name="labdarúgóTípus">
        <xs:sequence>
            <xs:element ref="Poszt" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="Név">
                <xs:complexType>
                    <xs:sequence>
                         <xs:element ref="Keresztnév" />
                        <xs:element ref="Vezetéknév" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="Gól" />
            <xs:element ref="Mezszám" />
            <xs:element ref="Szülidő" />
        </xs:sequence>
            <xs:attribute name="Lkód" type="xs:ID" use="required" />
            <xs:attribute name="CSkód" type="xs:integer" />
    </xs:complexType>  
    <xs:complexType name="mérkőzésTípus">        
        <xs:sequence>
            <xs:element ref="Csapat1Gólok" />
            <xs:element ref="Csapat2Gólok" />
         </xs:sequence>
            <xs:attribute name="Mkód" type="xs:integer" use="required" />
            <xs:attribute name="Tkód" type="xs:integer" />
            <xs:attribute name="Hkód" type="xs:integer" />
     </xs:complexType>
    <xs:complexType name="helyszínTípus">
        <xs:sequence>
            <xs:element name="Stadion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="Név" />
                        <xs:element ref="Férőhely" />
                        <xs:element ref="Tulajdonos"  />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Város" />
        </xs:sequence>
            <xs:attribute name="Hkód" type="xs:integer" use="required" />
    </xs:complexType>       
    <xs:complexType name="típus">
            <xs:sequence>
                <xs:element ref="Név" />
            </xs:sequence>
            <xs:attribute name="Tkód" type="xs:integer" use="required" />
    </xs:complexType>
     <xs:complexType name="mérkőzikTípus">
        <xs:sequence>
            <xs:element ref="Dátum" />
        </xs:sequence>
            <xs:attribute name="Mkód" type="xs:integer" use="required" />
            <xs:attribute name="Csapat1" type="xs:integer" />
            <xs:attribute name="Csapat2" type="xs:integer" />
            <xs:attribute name="Győztes" type="xs:integer" />
    </xs:complexType>   
   <!--Gyökérelemtől az elemek felhasználása-->
    <xs:element name="Világbajnokság_DLWGQZ">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Csapat" type="csapatTípus" minOccurs="1" maxOccurs="100"/>
                <xs:element name="Logó" type="logóTípus" minOccurs="1" maxOccurs="100"/>
                <xs:element name="Csoport" type="csoportTípus" minOccurs="1" maxOccurs="10"/>
                <xs:element name="Labdarúgó" type="labdarúgóTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Mérkőzés" type="mérkőzésTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Helyszín" type="helyszínTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Típus" type="típus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Mérkőzik" type="mérkőzikTípus" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>   
        <!--Elsődleges kulcsok-->
        <xs:key name="csapat_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@CSkód"/>
        </xs:key>
        <xs:key name="logó_kulcs">
            <xs:selector xpath="Logó"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:key>
        <xs:key name="csoport_kulcs">
            <xs:selector xpath="Csoport"/>
            <xs:field xpath="@CSOPkód"/>
        </xs:key>
        <xs:key name="labdarúgó_kulcs">
            <xs:selector xpath="Labdarúgó"/>
            <xs:field xpath="@Lkód"/>
        </xs:key>
        <xs:key name="mérkőzés_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Mkód"/>
        </xs:key>
        <xs:key name="helyszín_kulcs">
            <xs:selector xpath="Helyszín"/>
            <xs:field xpath="@Hkód"/>
        </xs:key>
        <xs:key name="típus_kulcs">
            <xs:selector xpath="Típus"/>
            <xs:field xpath="@Tkód"/>
        </xs:key>
        <!--Idegen kulcsok-->
        <xs:keyref name="csapat_labdarúgó_kulcs" refer="csapat_kulcs">
            <xs:selector xpath="Labdarúgó"/>
            <xs:field xpath="@CSkód"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_csapat1" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Csapat1"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_csapat2" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Csapat2"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_győztes" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Győztes"/>
        </xs:keyref>
        <xs:keyref name="logó_csapat_kulcs" refer="logó_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:keyref>
        <xs:keyref name="csoport_csapat_kulcs" refer="csoport_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@CSOPkód"/>
        </xs:keyref>
        <xs:keyref name="labdarúgó_csapat_kulcs" refer="labdarúgó_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@Csapatkapitány"/>
        </xs:keyref>
        <xs:keyref name="mérkőzés_mérkőzik_kulcs" refer="mérkőzés_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Mkód"/>
        </xs:keyref>
        <xs:keyref name="helyszín_mérkőzés_kulcs" refer="helyszín_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Hkód"/>
        </xs:keyref>
        <xs:keyref name="típus_mérkőzés_kulcs" refer="típus_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Tkód"/>
        </xs:keyref>
        <!--Az 1:1 kapcsolat megvalósítás-->
        <xs:unique name="logó_csapat_egyegy">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:unique>   
    </xs:element>
</xs:schema>

=== szkarosisz1/DLWGQZ_XMLGyak/XMLTaskDLWGQZ/DOMParseDLWGQZ/XMLDLWGQZ.xml
<?xml version="1.0" encoding="UTF-8"?>
<Világbajnokság_DLWGQZ xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaDLWGQZ.xsd">
    <!--Csapatok-->
    <Csapat CSkód="1" Csapatkapitány="CR7" CSOPkód="11" LOGÓkód="21">
        <Vezetőedző>Roberto Martínez</Vezetőedző>
        <Név>Portugália</Név>    
    </Csapat>   
    <Csapat CSkód="2" Csapatkapitány="TS1" CSOPkód="12" LOGÓkód="22">
        <Vezetőedző>Hansi Flick</Vezetőedző>
        <Név>Németország</Név>    
    </Csapat> 
    <Csapat CSkód="3" Csapatkapitány="KM10" CSOPkód="13" LOGÓkód="23">
        <Vezetőedző>Didier Deschamp</Vezetőedző>
        <Név>Franciaország</Név>    
    </Csapat> 
    <Csapat CSkód="4" Csapatkapitány="HK9" CSOPkód="14" LOGÓkód="24">
        <Vezetőedző>Gareth Southgate</Vezetőedző>
        <Név>Anglia</Név>    
    </Csapat> 
    <Csapat CSkód="5" Csapatkapitány="LM10" CSOPkód="15" LOGÓkód="25">
        <Vezetőedző>Lionel Scaloni</Vezetőedző>
        <Név>Argentína</Név>    
    </Csapat> 
    <!--Logók-->
    <Logó LOGÓkód="21">
        <Színek>Piros</Színek>
        <Színek>Kék</Színek>
        <Színek>Zöld</Színek>
        <Tervező>António Modesto</Tervező>
    </Logó>
    <Logó LOGÓkód="22">
        <Színek>Fekete</Színek>
        <Színek>Piros</Színek>
        <Színek>Arany</Színek>
        <Tervező>Anton Stankowski</Tervező>
    </Logó>
    <Logó LOGÓkód="23">
        <Színek>Kék</Színek>
        <Színek>Fehér</Színek>
        <Színek>Piros</Színek>
        <Tervező>Raymond Savignac</Tervező>
    </Logó>
    <Logó LOGÓkód="24">
        <Színek>Fehér</Színek>
        <Színek>Kék</Színek>
        <Színek>Piros</Színek>
        <Tervező>William C. Gibbons</Tervező>
    </Logó>
    <Logó LOGÓkód="25">
        <Színek>Égkék</Színek>
        <Színek>Fehér</Színek>
        <Színek>Sárga</Színek>
        <Tervező>Salvador Dellutri</Tervező>
    </Logó>
    <!--Csoportok-->
    <Csoport CSOPkód="11">
        <Jelölés>A</Jelölés>
    </Csoport>
    <Csoport CSOPkód="12">
        <Jelölés>B</Jelölés>
    </Csoport>
    <Csoport CSOPkód="13">
        <Jelölés>C</Jelölés>
    </Csoport>
    <Csoport CSOPkód="14">
        <Jelölés>D</Jelölés>
    </Csoport>
    <Csoport CSOPkód="15">
        <Jelölés>E</Jelölés>
    </Csoport>
    <!--Labdarúgók-->
    <!--PORTUGÁL Labdarúgók-->
    <Labdarúgó Lkód="CR7" CSkód="1">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Cristiano</Keresztnév>
            <Vezetéknév>Ronaldo</Vezetéknév>
        </Név>
        <Gól>10</Gól>
        <Mezszám>7</Mezszám>
        <Szülidő>1985.02.05</Szülidő>
    </Labdarúgó>
    <Labdarúgó Lkód="RN18" CSkód="1">
        <Poszt>Középpályás</Poszt>
        <Poszt>Védekező középpályás</Poszt>
        <Név>
            <Keresztnév>Ruben</Keresztnév>
            <Vezetéknév>Neves</Vezetéknév>
        </Név>
        <Gól>2</Gól>
        <Mezszám>18</Mezszám>
        <Szülidő>1997.03.13</Szülidő>
    </Labdarúgó>
    <!--NÉMET Labdarúgók-->
    <Labdarúgó Lkód="TS1" CSkód="2">
        <Poszt>Kapus</Poszt>
        <Név>
            <Keresztnév>Marc-André</Keresztnév>
            <Vezetéknév>ter Stegen</Vezetéknév>
        </Név>
        <Gól>0</Gól>
        <Mezszám>22</Mezszám>
        <Szülidő>1992.04.05</Szülidő>
    </Labdarúgó>
    <Labdarúgó Lkód="JK6" CSkód="2">
        <Poszt>Középpályás</Poszt>
        <Poszt>Jobb szélső védő</Poszt>
        <Név>
            <Keresztnév>Joshua</Keresztnév>
            <Vezetéknév>Kimmich</Vezetéknév>
        </Név>
        <Gól>3</Gól>
        <Mezszám>6</Mezszám>
        <Szülidő>1995.02.08</Szülidő>
    </Labdarúgó>
    <!--FRANCIA Labdarúgók-->
    <Labdarúgó Lkód="KM10" CSkód="3">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Kylian</Keresztnév>
            <Vezetéknév>Mbappé</Vezetéknév>
        </Név>
        <Gól>9</Gól>
        <Mezszám>10</Mezszám>
        <Szülidő>1998.12.20</Szülidő>
    </Labdarúgó>
    <Labdarúgó Lkód="EC25" CSkód="3">
        <Poszt>Középpályás</Poszt>
        <Poszt>Védekező középpályás</Poszt>
        <Poszt>Bal szélső védő</Poszt>
        <Név>
            <Keresztnév>Eduardo</Keresztnév>
            <Vezetéknév>Camavinga</Vezetéknév>
        </Név>
        <Gól>3</Gól>
        <Mezszám>25</Mezszám>
        <Szülidő>2002.11.10</Szülidő>
    </Labdarúgó>
    <!--ANGOL Labdarúgók-->
    <Labdarúgó Lkód="HK9" CSkód="4">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Harry</Keresztnév>
            <Vezetéknév>Kane</Vezetéknév>
        </Név>
        <Gól>7</Gól>
        <Mezszám>9</Mezszám>
        <Szülidő>1993.07.28</Szülidő>
    </Labdarúgó>
    <Labdarúgó Lkód="JB10" CSkód="4">
        <Poszt>Középpályás</Poszt>
        <Név>
            <Keresztnév>Jude</Keresztnév>
            <Vezetéknév>Bellingham</Vezetéknév>
        </Név>
        <Gól>6</Gól>
        <Mezszám>10</Mezszám>
        <Szülidő>2003.06.29</Szülidő>
    </Labdarúgó>
    <!--ARGENTÍN Labdarúgók-->
    <Labdarúgó Lkód="LM10" CSkód="5">
        <Poszt>Középcsatár</Poszt>
        <Poszt>Jobb szélső csatár</Poszt>
        <Név>
            <Keresztnév>Lionel</Keresztnév>
            <Vezetéknév>Messi</Vezetéknév>
        </Név>
        <Gól>9</Gól>
        <Mezszám>10</Mezszám>
        <Szülidő>1987.07.24</Szülidő>
    </Labdarúgó>
    <Labdarúgó Lkód="EM23" CSkód="5">
        <Poszt>Kapus</Poszt>
        <Név>
            <Keresztnév>Emiliano</Keresztnév>
            <Vezetéknév>Martinez</Vezetéknév>
        </Név>
        <Gól>0</Gól>
        <Mezszám>23</Mezszám>
        <Szülidő>1992.09.02</Szülidő>
    </Labdarúgó>
    <!--Mérkőzések-->
    <Mérkőzés Mkód="1" Tkód="101" Hkód="201">
        <Csapat1Gólok>5</Csapat1Gólok>
        <Csapat2Gólok>2</Csapat2Gólok>
    </Mérkőzés>
    <Mérkőzés Mkód="2" Tkód="102" Hkód="202">
        <Csapat1Gólok>0</Csapat1Gólok>
        <Csapat2Gólok>1</Csapat2Gólok>
    </Mérkőzés>
    <Mérkőzés Mkód="3" Tkód="103" Hkód="203">
        <Csapat1Gólok>3</Csapat1Gólok>
        <Csapat2Gólok>7</Csapat2Gólok>
    </Mérkőzés>
    <Mérkőzés Mkód="4" Tkód="104" Hkód="204">
        <Csapat1Gólok>2</Csapat1Gólok>
        <Csapat2Gólok>1</Csapat2Gólok>
    </Mérkőzés>
    <Mérkőzés Mkód="5" Tkód="105" Hkód="205">
        <Csapat1Gólok>2</Csapat1Gólok>
        <Csapat2Gólok>3</Csapat2Gólok>
    </Mérkőzés>
    <!--Helyszínek-->
    <Helyszín Hkód="201">
        <Stadion>
            <Név>Education City Stadion</Név>
            <Férőhely>45000</Férőhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Rajján</Város>
    </Helyszín>
    <Helyszín Hkód="202">
        <Stadion>
            <Név>Al Bayt Stadion</Név>
            <Férőhely>60000</Férőhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Hor</Város>
    </Helyszín>
    <Helyszín Hkód="203">
        <Stadion>
            <Név>Loszaíli Nemzeti Stadion</Név>
            <Férőhely>80000</Férőhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>Loszaíl</Város>
    </Helyszín>
    <Helyszín Hkód="204">
        <Stadion>
            <Név>al-Thumama Stadion</Név>
            <Férőhely>40000</Férőhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Thumama</Város>
    </Helyszín>
    <Helyszín Hkód="205">
        <Stadion>
            <Név>El-Dzsanúb Stadion</Név>
            <Férőhely>40000</Férőhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>Al-Vakra</Város>
    </Helyszín>
    <!--Típusok-->
    <Típus Tkód="101">
        <Név>Csoportmérkőzés</Név>
    </Típus>
    <Típus Tkód="102">  
        <Név>Nyolcaddöntő</Név>
    </Típus>
    <Típus Tkód="103">
        <Név>Negyeddöntő</Név>
    </Típus>
    <Típus Tkód="104">
        <Név>Elődöntő</Név>
    </Típus>
    <Típus Tkód="105">
        <Név>Döntő</Név>
    </Típus>
    <!--Mérkőzik kapcsolat-->
    <Mérkőzik Mkód="1" Csapat1="1" Csapat2="2" Győztes="1">
        <Dátum>2022.11.22</Dátum>
        <Játékvezető>Frank de Bleeckere</Játékvezető>
    </Mérkőzik>
    <Mérkőzik Mkód="2" Csapat1="3" Csapat2="5" Győztes="5">
        <Dátum>2022.11.26</Dátum>
        <Játékvezető>Pedro Proenca</Játékvezető>
    </Mérkőzik>
    <Mérkőzik Mkód="3" Csapat1="2" Csapat2="1" Győztes="2">
        <Dátum>2022.11.30</Dátum>
        <Játékvezető>Kim Milton Nielsen</Játékvezető>
    </Mérkőzik>
    <Mérkőzik Mkód="4" Csapat1="4" Csapat2="5" Győztes="4">
        <Dátum>2022.12.01</Dátum>
        <Játékvezető>Michel Vautrot</Játékvezető>
    </Mérkőzik>
    <Mérkőzik Mkód="5" Csapat1="1" Csapat2="5" Győztes="1">
        <Dátum>2022.12.18</Dátum>
        <Játékvezető>Oscar Ruiz</Játékvezető>
    </Mérkőzik>
</Világbajnokság_DLWGQZ>

=== szkarosisz1/DLWGQZ_XMLGyak/XMLTaskDLWGQZ/DOMParseDLWGQZ/XMLDLWGQZ3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Világbajnokság_DLWGQZ xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaDLWGQZ.xsd">
    <!--Csapatok-->
    <Csapat CSkód="1" Csapatkapitány="CR7" CSOPkód="11" LOGÓkód="21">
        <Vezetõedzõ>Roberto Martínez</Vezetõedzõ>
        <Név>Portugália</Név>    
    </Csapat>   
    <Csapat CSkód="2" Csapatkapitány="TS1" CSOPkód="12" LOGÓkód="22">
        <Vezetõedzõ>Hansi Flick</Vezetõedzõ>
        <Név>Németország</Név>    
    </Csapat> 
    <Csapat CSkód="3" Csapatkapitány="KM10" CSOPkód="13" LOGÓkód="23">
        <Vezetõedzõ>Didier Deschamp</Vezetõedzõ>
        <Név>Franciaország</Név>    
    </Csapat> 
    <Csapat CSkód="4" Csapatkapitány="HK9" CSOPkód="14" LOGÓkód="24">
        <Vezetõedzõ>Gareth Southgate</Vezetõedzõ>
        <Név>Anglia</Név>    
    </Csapat> 
    <Csapat CSkód="5" Csapatkapitány="LM10" CSOPkód="15" LOGÓkód="25">
        <Vezetõedzõ>Lionel Scaloni</Vezetõedzõ>
        <Név>Argentína</Név>    
    </Csapat> 
    <!--Logók-->
    <Logó LOGÓkód="21">
        <Színek>Piros</Színek>
        <Színek>Kék</Színek>
        <Színek>Zöld</Színek>
        <Tervezõ>António Modesto</Tervezõ>
    </Logó>
    <Logó LOGÓkód="22">
        <Színek>Fekete</Színek>
        <Színek>Piros</Színek>
        <Színek>Arany</Színek>
        <Tervezõ>Anton Stankowski</Tervezõ>
    </Logó>
    <Logó LOGÓkód="23">
        <Színek>Kék</Színek>
        <Színek>Fehér</Színek>
        <Színek>Piros</Színek>
        <Tervezõ>Raymond Savignac</Tervezõ>
    </Logó>
    <Logó LOGÓkód="24">
        <Színek>Fehér</Színek>
        <Színek>Kék</Színek>
        <Színek>Piros</Színek>
        <Tervezõ>William C. Gibbons</Tervezõ>
    </Logó>
    <Logó LOGÓkód="25">
        <Színek>Égkék</Színek>
        <Színek>Fehér</Színek>
        <Színek>Sárga</Színek>
        <Tervezõ>Salvador Dellutri</Tervezõ>
    </Logó>
    <!--Csoportok-->
    <Csoport CSOPkód="11">
        <Jelölés>A</Jelölés>
    </Csoport>
    <Csoport CSOPkód="12">
        <Jelölés>B</Jelölés>
    </Csoport>
    <Csoport CSOPkód="13">
        <Jelölés>C</Jelölés>
    </Csoport>
    <Csoport CSOPkód="14">
        <Jelölés>D</Jelölés>
    </Csoport>
    <Csoport CSOPkód="15">
        <Jelölés>E</Jelölés>
    </Csoport>
    <!--Labdarúgók-->
    <!--PORTUGÁL Labdarúgók-->
    <Labdarúgó Lkód="CR7" CSkód="1">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Cristiano</Keresztnév>
            <Vezetéknév>Ronaldo</Vezetéknév>
        </Név>
        <Gól>10</Gól>
        <Mezszám>7</Mezszám>
        <Szülidõ>1985.02.05</Szülidõ>
    </Labdarúgó>
    <Labdarúgó Lkód="RN18" CSkód="1">
        <Poszt>Középpályás</Poszt>
        <Poszt>Védekezõ középpályás</Poszt>
        <Név>
            <Keresztnév>Ruben</Keresztnév>
            <Vezetéknév>Neves</Vezetéknév>
        </Név>
        <Gól>2</Gól>
        <Mezszám>18</Mezszám>
        <Szülidõ>1997.03.13</Szülidõ>
    </Labdarúgó>
    <!--NÉMET Labdarúgók-->
    <Labdarúgó Lkód="TS1" CSkód="2">
        <Poszt>Kapus</Poszt>
        <Név>
            <Keresztnév>Marc-André</Keresztnév>
            <Vezetéknév>ter Stegen</Vezetéknév>
        </Név>
        <Gól>0</Gól>
        <Mezszám>22</Mezszám>
        <Szülidõ>1992.04.05</Szülidõ>
    </Labdarúgó>
    <Labdarúgó Lkód="JK6" CSkód="2">
        <Poszt>Középpályás</Poszt>
        <Poszt>Jobb szélsõ védõ</Poszt>
        <Név>
            <Keresztnév>Joshua</Keresztnév>
            <Vezetéknév>Kimmich</Vezetéknév>
        </Név>
        <Gól>3</Gól>
        <Mezszám>6</Mezszám>
        <Szülidõ>1995.02.08</Szülidõ>
    </Labdarúgó>
    <!--FRANCIA Labdarúgók-->
    <Labdarúgó Lkód="KM10" CSkód="3">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Kylian</Keresztnév>
            <Vezetéknév>Mbappé</Vezetéknév>
        </Név>
        <Gól>9</Gól>
        <Mezszám>10</Mezszám>
        <Szülidõ>1998.12.20</Szülidõ>
    </Labdarúgó>
    <Labdarúgó Lkód="EC25" CSkód="3">
        <Poszt>Középpályás</Poszt>
        <Poszt>Védekezõ középpályás</Poszt>
        <Poszt>Bal szélsõ védõ</Poszt>
        <Név>
            <Keresztnév>Eduardo</Keresztnév>
            <Vezetéknév>Camavinga</Vezetéknév>
        </Név>
        <Gól>3</Gól>
        <Mezszám>25</Mezszám>
        <Szülidõ>2002.11.10</Szülidõ>
    </Labdarúgó>
    <!--ANGOL Labdarúgók-->
    <Labdarúgó Lkód="HK9" CSkód="4">
        <Poszt>Középcsatár</Poszt>
        <Név>
            <Keresztnév>Harry</Keresztnév>
            <Vezetéknév>Kane</Vezetéknév>
        </Név>
        <Gól>7</Gól>
        <Mezszám>9</Mezszám>
        <Szülidõ>1993.07.28</Szülidõ>
    </Labdarúgó>
    <Labdarúgó Lkód="JB10" CSkód="4">
        <Poszt>Középpályás</Poszt>
        <Név>
            <Keresztnév>Jude</Keresztnév>
            <Vezetéknév>Bellingham</Vezetéknév>
        </Név>
        <Gól>6</Gól>
        <Mezszám>10</Mezszám>
        <Szülidõ>2003.06.29</Szülidõ>
    </Labdarúgó>
    <!--ARGENTÍN Labdarúgók-->
    <Labdarúgó Lkód="LM10" CSkód="5">
        <Poszt>Középcsatár</Poszt>
        <Poszt>Jobb szélsõ csatár</Poszt>
        <Név>
            <Keresztnév>Lionel</Keresztnév>
            <Vezetéknév>Messi</Vezetéknév>
        </Név>
        <Gól>9</Gól>
        <Mezszám>10</Mezszám>
        <Szülidõ>1987.07.24</Szülidõ>
    </Labdarúgó>
    <Labdarúgó Lkód="EM23" CSkód="5">
        <Poszt>Kapus</Poszt>
        <Név>
            <Keresztnév>Emiliano</Keresztnév>
            <Vezetéknév>Martinez</Vezetéknév>
        </Név>
        <Gól>0</Gól>
        <Mezszám>23</Mezszám>
        <Szülidõ>1992.09.02</Szülidõ>
    </Labdarúgó>
    <!--Mérkõzések-->
    <Mérkõzés Mkód="1" Tkód="101" Hkód="201">
        <Csapat1Gólok>5</Csapat1Gólok>
        <Csapat2Gólok>2</Csapat2Gólok>
    </Mérkõzés>
    <Mérkõzés Mkód="2" Tkód="102" Hkód="202">
        <Csapat1Gólok>0</Csapat1Gólok>
        <Csapat2Gólok>1</Csapat2Gólok>
    </Mérkõzés>
    <Mérkõzés Mkód="3" Tkód="103" Hkód="203">
        <Csapat1Gólok>3</Csapat1Gólok>
        <Csapat2Gólok>7</Csapat2Gólok>
    </Mérkõzés>
    <Mérkõzés Mkód="4" Tkód="104" Hkód="204">
        <Csapat1Gólok>2</Csapat1Gólok>
        <Csapat2Gólok>1</Csapat2Gólok>
    </Mérkõzés>
    <Mérkõzés Mkód="5" Tkód="105" Hkód="205">
        <Csapat1Gólok>2</Csapat1Gólok>
        <Csapat2Gólok>3</Csapat2Gólok>
    </Mérkõzés>
    <!--Helyszínek-->
    <Helyszín Hkód="201">
        <Stadion>
            <Név>Education City Stadion</Név>
            <Férõhely>45000</Férõhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Rajján</Város>
    </Helyszín>
    <Helyszín Hkód="202">
        <Stadion>
            <Név>Al Bayt Stadion</Név>
            <Férõhely>60000</Férõhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Hor</Város>
    </Helyszín>
    <Helyszín Hkód="203">
        <Stadion>
            <Név>Loszaíli Nemzeti Stadion</Név>
            <Férõhely>80000</Férõhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>Loszaíl</Város>
    </Helyszín>
    <Helyszín Hkód="204">
        <Stadion>
            <Név>al-Thumama Stadion</Név>
            <Férõhely>40000</Férõhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>al-Thumama</Város>
    </Helyszín>
    <Helyszín Hkód="205">
        <Stadion>
            <Név>El-Dzsanúb Stadion</Név>
            <Férõhely>40000</Férõhely>
            <Tulajdonos>katari kormány</Tulajdonos>
        </Stadion>
        <Város>Al-Vakra</Város>
    </Helyszín>
    <!--Típusok-->
    <Típus Tkód="101">
        <Név>Csoportmérkõzés</Név>
    </Típus>
    <Típus Tkód="102">  
        <Név>Nyolcaddöntõ</Név>
    </Típus>
    <Típus Tkód="103">
        <Név>Negyeddöntõ</Név>
    </Típus>
    <Típus Tkód="104">
        <Név>Elõdöntõ</Név>
    </Típus>
    <Típus Tkód="105">
        <Név>Döntõ</Név>
    </Típus>
    <!--Mérkõzik kapcsolat-->
    <Mérkõzik Mkód="1" Csapat1="1" Csapat2="2" Gyõztes="1">
        <Dátum>2022.11.22</Dátum>
        <Játékvezetõ>Frank de Bleeckere</Játékvezetõ>
    </Mérkõzik>
    <Mérkõzik Mkód="2" Csapat1="3" Csapat2="5" Gyõztes="5">
        <Dátum>2022.11.26</Dátum>
        <Játékvezetõ>Pedro Proenca</Játékvezetõ>
    </Mérkõzik>
    <Mérkõzik Mkód="3" Csapat1="2" Csapat2="1" Gyõztes="2">
        <Dátum>2022.11.30</Dátum>
        <Játékvezetõ>Kim Milton Nielsen</Játékvezetõ>
    </Mérkõzik>
    <Mérkõzik Mkód="4" Csapat1="4" Csapat2="5" Gyõztes="4">
        <Dátum>2022.12.01</Dátum>
        <Játékvezetõ>Michel Vautrot</Játékvezetõ>
    </Mérkõzik>
    <Mérkõzik Mkód="5" Csapat1="1" Csapat2="5" Gyõztes="1">
        <Dátum>2022.12.18</Dátum>
        <Játékvezetõ>Oscar Ruiz</Játékvezetõ>
    </Mérkõzik>
</Világbajnokság_DLWGQZ>
