=== szkarosisz1/DLWGQZ_XMLGyak/XMLTaskDLWGQZ/XMLSchemaDLWGQZ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--Egyszerű típusok kigyűjtése-->
    <!--Csapat-->
    <xs:element name="Vezetőedző" type="xs:string" />
    <xs:element name="Név" type="xs:string" />
    <!--Logó-->
    <xs:element name="Színek" type="xs:string" />
    <xs:element name="Tervező" type="xs:string" />
    <!--Csoport-->
    <xs:element name="Jelölés" type="jelolesTipus" />
    <!--Labdarúgó-->
    <xs:element name="Poszt" type="xs:string" />
    <xs:element name="Keresztnév" type="xs:string" />
    <xs:element name="Vezetéknév" type="xs:string" />
    <xs:element name="Gól" type="golTipus" />
    <xs:element name="Mezszám" type="xs:int" />
    <xs:element name="Szülidő" type="datumTipus" />
    <!--Mérkőzés-->
    <xs:element name="Csapat1Gólok" type="golTipus" />
    <xs:element name="Csapat2Gólok" type="golTipus" />
    <!--Helyszín-->
    <xs:element name="Férőhely" type="ferohelyTipus" />
    <xs:element name="Tulajdonos" type="xs:string" />    
    <xs:element name="Város" type="xs:string"/>  
    <!--Mérkőzik-->
    <xs:element name="Dátum" type="datumTipus" />
    <!--Saját típusok meghatározása-->
    <xs:simpleType name="jelolesTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D" />
            <xs:enumeration value="E" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ferohelyTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="30000" />
            <xs:maxInclusive value="100000" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="golTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="10" />
    </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="datumTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>    
    <!--Komplex típusokhoz saját típus meghatározása-->
    <xs:complexType name="csapatTípus">
        <xs:sequence>        
            <xs:element ref="Vezetőedző" />
            <xs:element ref="Név" />
        </xs:sequence>
            <xs:attribute name="CSkód" type="xs:integer" use="required" />
            <xs:attribute name="Csapatkapitány" type="xs:string" />
            <xs:attribute name="CSOPkód" type="xs:integer" />
            <xs:attribute name="LOGÓkód" type="xs:integer" />
    </xs:complexType>    
    <xs:complexType name="logóTípus">
        <xs:sequence>          
            <xs:element ref="Színek" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="Tervező" />
        </xs:sequence>
            <xs:attribute name="LOGÓkód" type="xs:integer" use="required" />
    </xs:complexType>         
    <xs:complexType name="csoportTípus">        
        <xs:sequence>
            <xs:element ref="Jelölés" />
        </xs:sequence>
                <xs:attribute name="CSOPkód" type="xs:integer" use="required" />
    </xs:complexType>   
    <xs:complexType name="labdarúgóTípus">
        <xs:sequence>
            <xs:element ref="Poszt" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="Név">
                <xs:complexType>
                    <xs:sequence>
                         <xs:element ref="Keresztnév" />
                        <xs:element ref="Vezetéknév" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="Gól" />
            <xs:element ref="Mezszám" />
            <xs:element ref="Szülidő" />
        </xs:sequence>
            <xs:attribute name="Lkód" type="xs:ID" use="required" />
            <xs:attribute name="CSkód" type="xs:integer" />
    </xs:complexType>  
    <xs:complexType name="mérkőzésTípus">        
        <xs:sequence>
            <xs:element ref="Csapat1Gólok" />
            <xs:element ref="Csapat2Gólok" />
         </xs:sequence>
            <xs:attribute name="Mkód" type="xs:integer" use="required" />
            <xs:attribute name="Tkód" type="xs:integer" />
            <xs:attribute name="Hkód" type="xs:integer" />
     </xs:complexType>
    <xs:complexType name="helyszínTípus">
        <xs:sequence>
            <xs:element name="Stadion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="Név" />
                        <xs:element ref="Férőhely" />
                        <xs:element ref="Tulajdonos"  />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Város" />
        </xs:sequence>
            <xs:attribute name="Hkód" type="xs:integer" use="required" />
    </xs:complexType>       
    <xs:complexType name="típus">
            <xs:sequence>
                <xs:element ref="Név" />
            </xs:sequence>
            <xs:attribute name="Tkód" type="xs:integer" use="required" />
    </xs:complexType>
     <xs:complexType name="mérkőzikTípus">
        <xs:sequence>
            <xs:element ref="Dátum" />
        </xs:sequence>
            <xs:attribute name="Mkód" type="xs:integer" use="required" />
            <xs:attribute name="Csapat1" type="xs:integer" />
            <xs:attribute name="Csapat2" type="xs:integer" />
            <xs:attribute name="Győztes" type="xs:integer" />
    </xs:complexType>   
   <!--Gyökérelemtől az elemek felhasználása-->
    <xs:element name="Világbajnokság_DLWGQZ">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Csapat" type="csapatTípus" minOccurs="1" maxOccurs="100"/>
                <xs:element name="Logó" type="logóTípus" minOccurs="1" maxOccurs="100"/>
                <xs:element name="Csoport" type="csoportTípus" minOccurs="1" maxOccurs="10"/>
                <xs:element name="Labdarúgó" type="labdarúgóTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Mérkőzés" type="mérkőzésTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Helyszín" type="helyszínTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Típus" type="típus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Mérkőzik" type="mérkőzikTípus" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>   
        <!--Elsődleges kulcsok-->
        <xs:key name="csapat_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@CSkód"/>
        </xs:key>
        <xs:key name="logó_kulcs">
            <xs:selector xpath="Logó"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:key>
        <xs:key name="csoport_kulcs">
            <xs:selector xpath="Csoport"/>
            <xs:field xpath="@CSOPkód"/>
        </xs:key>
        <xs:key name="labdarúgó_kulcs">
            <xs:selector xpath="Labdarúgó"/>
            <xs:field xpath="@Lkód"/>
        </xs:key>
        <xs:key name="mérkőzés_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Mkód"/>
        </xs:key>
        <xs:key name="helyszín_kulcs">
            <xs:selector xpath="Helyszín"/>
            <xs:field xpath="@Hkód"/>
        </xs:key>
        <xs:key name="típus_kulcs">
            <xs:selector xpath="Típus"/>
            <xs:field xpath="@Tkód"/>
        </xs:key>
        <!--Idegen kulcsok-->
        <xs:keyref name="csapat_labdarúgó_kulcs" refer="csapat_kulcs">
            <xs:selector xpath="Labdarúgó"/>
            <xs:field xpath="@CSkód"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_csapat1" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Csapat1"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_csapat2" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Csapat2"/>
        </xs:keyref>
        <xs:keyref name="csapat_mérkőzik_kulcs_győztes" refer="csapat_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Győztes"/>
        </xs:keyref>
        <xs:keyref name="logó_csapat_kulcs" refer="logó_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:keyref>
        <xs:keyref name="csoport_csapat_kulcs" refer="csoport_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@CSOPkód"/>
        </xs:keyref>
        <xs:keyref name="labdarúgó_csapat_kulcs" refer="labdarúgó_kulcs">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@Csapatkapitány"/>
        </xs:keyref>
        <xs:keyref name="mérkőzés_mérkőzik_kulcs" refer="mérkőzés_kulcs">
            <xs:selector xpath="Mérkőzik"/>
            <xs:field xpath="@Mkód"/>
        </xs:keyref>
        <xs:keyref name="helyszín_mérkőzés_kulcs" refer="helyszín_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Hkód"/>
        </xs:keyref>
        <xs:keyref name="típus_mérkőzés_kulcs" refer="típus_kulcs">
            <xs:selector xpath="Mérkőzés"/>
            <xs:field xpath="@Tkód"/>
        </xs:keyref>
        <!--Az 1:1 kapcsolat megvalósítás-->
        <xs:unique name="logó_csapat_egyegy">
            <xs:selector xpath="Csapat"/>
            <xs:field xpath="@LOGÓkód"/>
        </xs:unique>   
    </xs:element>
</xs:schema>

=== szkarosisz1/DLWGQZ_XMLGyak/XMLTaskDLWGQZ/DOMParseDLWGQZ/XMLDLWGQZ1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Világbajnokság_DLWGQZ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaDLWGQZ.xsd">
 <Csapat CSOPkód="11" CSkód="1" Csapatkapitány="CR7" LOGÓkód="21">
  <Vezetõedzõ >Roberto Martínez</Vezetõedzõ>
  <Név >Portugália</Név>
 </Csapat>

 <Csapat CSOPkód="12" CSkód="2" Csapatkapitány="TS1" LOGÓkód="22">
  <Vezetõedzõ >Hansi Flick</Vezetõedzõ>
  <Név >Németország</Név>
 </Csapat>

 <Csapat CSOPkód="13" CSkód="3" Csapatkapitány="KM10" LOGÓkód="23">
  <Vezetõedzõ >Didier Deschamp</Vezetõedzõ>
  <Név >Franciaország</Név>
 </Csapat>

 <Csapat CSOPkód="14" CSkód="4" Csapatkapitány="HK9" LOGÓkód="24">
  <Vezetõedzõ >Gareth Southgate</Vezetõedzõ>
  <Név >Anglia</Név>
 </Csapat>

 <Csapat CSOPkód="15" CSkód="5" Csapatkapitány="LM10" LOGÓkód="25">
  <Vezetõedzõ >Lionel Scaloni</Vezetõedzõ>
  <Név >Argentína</Név>
 </Csapat>


 <Logó LOGÓKód="21">
  <Színek >Piros</Színek>
  <Színek >Kék</Színek>
  <Színek >Zöld</Színek>
  <Tervezõ >António Modesto</Tervezõ>
 </Logó>

 <Logó LOGÓKód="22">
  <Színek >Fekete</Színek>
  <Színek >Piros</Színek>
  <Színek >Arany</Színek>
  <Tervezõ >Anton Stankowski</Tervezõ>
 </Logó>

 <Logó LOGÓKód="23">
  <Színek >Kék</Színek>
  <Színek >Fehér</Színek>
  <Színek >Piros</Színek>
  <Tervezõ >Raymond Savignac</Tervezõ>
 </Logó>

 <Logó LOGÓKód="24">
  <Színek >Fehér</Színek>
  <Színek >Kék</Színek>
  <Színek >Piros</Színek>
  <Tervezõ >William C. Gibbons</Tervezõ>
 </Logó>

 <Logó LOGÓKód="25">
  <Színek >Égkék</Színek>
  <Színek >Fehér</Színek>
  <Színek >Sárga</Színek>
  <Tervezõ >Salvador Dellutri</Tervezõ>
 </Logó>


 <Csoport CSOPkód="11">
  <Jelölés >A</Jelölés>
 </Csoport>

 <Csoport CSOPkód="12">
  <Jelölés >B</Jelölés>
 </Csoport>

 <Csoport CSOPkód="13">
  <Jelölés >C</Jelölés>
 </Csoport>

 <Csoport CSOPkód="14">
  <Jelölés >D</Jelölés>
 </Csoport>

 <Csoport CSOPkód="15">
  <Jelölés >E</Jelölés>
 </Csoport>


 <Labdarúgó CSkód="1" Lkód="CR7">
  <Poszt >Középcsatár</Poszt>
  <Név >
   <Keresztnév >Cristiano</Keresztnév>
   <Vezetéknév >Ronaldo</Vezetéknév>
  </Név>
  <Gól >10</Gól>
  <Mezszám >7</Mezszám>
  <Szülidõ >1985.02.05</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="1" Lkód="RN18">
  <Poszt >Középpályás</Poszt>
  <Poszt >Védekezõ középpályás</Poszt>
  <Név >
   <Keresztnév >Ruben</Keresztnév>
   <Vezetéknév >Neves</Vezetéknév>
  </Név>
  <Gól >2</Gól>
  <Mezszám >18</Mezszám>
  <Szülidõ >1997.03.13</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="2" Lkód="TS1">
  <Poszt >Kapus</Poszt>
  <Név >
   <Keresztnév >Marc-André</Keresztnév>
   <Vezetéknév >ter Stegen</Vezetéknév>
  </Név>
  <Gól >0</Gól>
  <Mezszám >22</Mezszám>
  <Szülidõ >1992.04.05</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="2" Lkód="JK6">
  <Poszt >Középpályás</Poszt>
  <Poszt >Jobb szélsõ védõ</Poszt>
  <Név >
   <Keresztnév >Joshua</Keresztnév>
   <Vezetéknév >Kimmich</Vezetéknév>
  </Név>
  <Gól >3</Gól>
  <Mezszám >6</Mezszám>
  <Szülidõ >1995.02.08</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="3" Lkód="KM10">
  <Poszt >Középcsatár</Poszt>
  <Név >
   <Keresztnév >Kylian</Keresztnév>
   <Vezetéknév >Mbappé</Vezetéknév>
  </Név>
  <Gól >9</Gól>
  <Mezszám >10</Mezszám>
  <Szülidõ >1998.12.20</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="3" Lkód="EC25">
  <Poszt >Középpályás</Poszt>
  <Poszt >Védekezõ középpályás</Poszt>
  <Poszt >Bal szélsõ védõ</Poszt>
  <Név >
   <Keresztnév >Eduardo</Keresztnév>
   <Vezetéknév >Camavinga</Vezetéknév>
  </Név>
  <Gól >3</Gól>
  <Mezszám >25</Mezszám>
  <Szülidõ >2002.11.10</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="4" Lkód="HK9">
  <Poszt >Középcsatár</Poszt>
  <Név >
   <Keresztnév >Harry</Keresztnév>
   <Vezetéknév >Kane</Vezetéknév>
  </Név>
  <Gól >7</Gól>
  <Mezszám >9</Mezszám>
  <Szülidõ >1993.07.28</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="4" Lkód="JB10">
  <Poszt >Középpályás</Poszt>
  <Név >
   <Keresztnév >Jude</Keresztnév>
   <Vezetéknév >Belligham</Vezetéknév>
  </Név>
  <Gól >6</Gól>
  <Mezszám >10</Mezszám>
  <Szülidõ >2003.06.29</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="5" Lkód="LM10">
  <Poszt >Középcsatár</Poszt>
  <Poszt >Jobb szélsõ csatár</Poszt>
  <Név >
   <Keresztnév >Lionel</Keresztnév>
   <Vezetéknév >Messi</Vezetéknév>
  </Név>
  <Gól >9</Gól>
  <Mezszám >10</Mezszám>
  <Szülidõ >1987.07.24</Szülidõ>
 </Labdarúgó>

 <Labdarúgó CSkód="5" Lkód="EM23">
  <Poszt >Kapus</Poszt>
  <Név >
   <Keresztnév >Emiliano</Keresztnév>
   <Vezetéknév >Martinez</Vezetéknév>
  </Név>
  <Gól >0</Gól>
  <Mezszám >23</Mezszám>
  <Szülidõ >1992.09.02</Szülidõ>
 </Labdarúgó>


 <Mérkõzés Hkód="201" Mkód="1" Tkód="101">
  <Csapat1Gólok >5</Csapat1Gólok>
  <Csapat2Gólok >2</Csapat2Gólok>
 </Mérkõzés>

 <Mérkõzés Hkód="202" Mkód="2" Tkód="102">
  <Csapat1Gólok >0</Csapat1Gólok>
  <Csapat2Gólok >1</Csapat2Gólok>
 </Mérkõzés>

 <Mérkõzés Hkód="203" Mkód="3" Tkód="103">
  <Csapat1Gólok >3</Csapat1Gólok>
  <Csapat2Gólok >7</Csapat2Gólok>
 </Mérkõzés>

 <Mérkõzés Hkód="204" Mkód="4" Tkód="104">
  <Csapat1Gólok >2</Csapat1Gólok>
  <Csapat2Gólok >1</Csapat2Gólok>
 </Mérkõzés>

 <Mérkõzés Hkód="205" Mkód="5" Tkód="104">
  <Csapat1Gólok >2</Csapat1Gólok>
  <Csapat2Gólok >3</Csapat2Gólok>
 </Mérkõzés>


 <Helyszín Hkód="201">
  <Stadion >
   <Név >Education City Stadion</Név>
   <Férõhely >45000</Férõhely>
   <Tulajdonos >katari kormány</Tulajdonos>
  </Stadion>
  <Város >al-Rajján</Város>
 </Helyszín>

 <Helyszín Hkód="202">
  <Stadion >
   <Név >Al Bayt Stadion</Név>
   <Férõhely >60000</Férõhely>
   <Tulajdonos >katari kormány</Tulajdonos>
  </Stadion>
  <Város >al-Hor</Város>
 </Helyszín>

 <Helyszín Hkód="203">
  <Stadion >
   <Név >Loszaíli Nemzeti Stadion</Név>
   <Férõhely >80000</Férõhely>
   <Tulajdonos >katari kormány</Tulajdonos>
  </Stadion>
  <Város >Loszaíl</Város>
 </Helyszín>

 <Helyszín Hkód="204">
  <Stadion >
   <Név >al-Thumama Stadion</Név>
   <Férõhely >40000</Férõhely>
   <Tulajdonos >katari kormány</Tulajdonos>
  </Stadion>
  <Város >al-Thumama</Város>
 </Helyszín>

 <Helyszín Hkód="205">
  <Stadion >
   <Név >El-Dzsanúb Stadion</Név>
   <Férõhely >40000</Férõhely>
   <Tulajdonos >katari kormány</Tulajdonos>
  </Stadion>
  <Város >Al-Vakra</Város>
 </Helyszín>


 <Típus Tkód="101">
  <Név >Csoportmérkõzés</Név>
 </Típus>

 <Típus Tkód="102">
  <Név >Nyolcaddöntõ</Név>
 </Típus>

 <Típus Tkód="103">
  <Név >Negyeddöntõ</Név>
 </Típus>

 <Típus Tkód="104">
  <Név >Elõdöntõ</Név>
 </Típus>

 <Típus Tkód="105">
  <Név >Döntõ</Név>
 </Típus>


 <Mérkõzik Csapat1="1" Csapat2="2" Gyõztes="1" Mkód="1">
  <Dátum >2022.11.22</Dátum>
  <Játékvezetõ >Frank de Bleeckere</Játékvezetõ>
 </Mérkõzik>

 <Mérkõzik Csapat1="3" Csapat2="5" Gyõztes="5" Mkód="2">
  <Dátum >2022.11.26</Dátum>
  <Játékvezetõ >Pedro Proenca</Játékvezetõ>
 </Mérkõzik>

 <Mérkõzik Csapat1="2" Csapat2="1" Gyõztes="2" Mkód="3">
  <Dátum >2022.11.30</Dátum>
  <Játékvezetõ >Kim Milton Nielsen</Játékvezetõ>
 </Mérkõzik>

 <Mérkõzik Csapat1="4" Csapat2="5" Gyõztes="4" Mkód="4">
  <Dátum >2022.12.01</Dátum>
  <Játékvezetõ >Michel Vautrot</Játékvezetõ>
 </Mérkõzik>

 <Mérkõzik Csapat1="1" Csapat2="5" Gyõztes="1" Mkód="5">
  <Dátum >2022.12.18</Dátum>
  <Játékvezetõ >Oscar Ruiz</Játékvezetõ>
 </Mérkõzik>


</Világbajnokság_DLWGQZ>
