=== szkarosisz1/DLWGQZ_XMLGyak/DLWGQZ_1004/DLWGQZ_ertodtd.dtd
<!ELEMENT DLWGQZ_modell (A,B,C)>
    <!ELEMENT A (b,c, B*)>
        <!ATTLIST A
            a ID #REQUIRED>
        
        <!ELEMENT b (x,y)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>
        <!ELEMENT c (d,e)>
            <!ELEMENT d (#PCDATA)>
            <!ELEMENT e (#PCDATA)>
        <!ELEMENT B (#PCDATA)>
    
    <!ELEMENT B (b, A*)>
        <!ATTLIST B
            a ID #REQUIRED>
        
        <!ELEMENT b (x,y)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>
        <!ELEMENT A (#PCDATA)>

    <!ELEMENT C (b, B)>
        <!ATTLIST C
            a ID #REQUIRED>

        <!ELEMENT b (#PCDATA)>
        <!ELEMENT B (#PCDATA)>

=== szkarosisz1/DLWGQZ_XMLGyak/DLWGQZ_1004/DLWGQZ_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DLWGQZ_modell SYSTEM "DLWGQZ_ertodtd.dtd">

<DLWGQZ_modell>

    <A a="1">
        <b>
            <x>x</x>
            <y>y</y>
        </b>
        <B>B</B>
        <c>
            <d>d</d>
            <e>e</e>
        </c>
    </A>

    <B a="1">
        <b>
            <x>x</x>
            <y>y</y>
        </b>
        <A>A</A>
    </B>

    <C a="1">
        <b>b</b>
        <B>B</B>
    </C>

</DLWGQZ_modell>
