=== szkarosisz1/DLWGQZ_XMLGyak/DLWGQZ_1011/DLWGQZ_kurzusfelvetel1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- elemi szintű típusok kigyűjtése-->
<xs:element name="hnev" type="xs:string"/>
<xs:element name="szulev" type="xs:string"/>
<xs:element name="kurzusnev" type="xs:string" />
<xs:element name="kredit" type="xs:string" />
<xs:element name="hely" type="xs:string" />
<xs:element name="idopont" type="xs:dateTime"/>
<xs:element name="oktato" type="xs:string" />
<xs:element name="oraado" type="xs:string" />

<!--attribútum szintű típusok kigyűjtése-->
<xs:attribute name="tanev"/>
<xs:attribute name="egyeten"/>
<xs:attribute name="evf" type="xs:integer"/>
<xs:attribute name="id"/>
<xs:attribute name="jovahagyas" />
<xs:attribute name="nyelv" />

    <xs:element name="kurzusfelvetel">
        <xs:complexType>
            <xs:attribute ref="tanev"/>
            <xs:attribute ref="egyeten"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="DLWGQZ_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzusfelvetel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hallgato">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="hnev"/>
                                        <xs:element ref="szulev"/>
                                        <xs:element name="szak">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute ref="evf"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="kurzusok">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="kurzus" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="kurzusnev"/>
                                                    <xs:element ref="kredit"/>
                                                    <xs:element ref="hely"/>
                                                    <xs:element ref="idopont"/>
                                                    <xs:element ref="oktato" minOccurs="0"/>
                                                    <xs:element ref="oraado"/>
                                                </xs:sequence>
                                                <xs:attribute ref="id"/>
                                                <xs:attribute ref="jovahagyas"/>
                                                <xs:attribute ref="nyelv" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== szkarosisz1/DLWGQZ_XMLGyak/DLWGQZ_1011/DLWGQZ_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<kurzusfelvetel tanev="2023/2024_1" egyeten="ME"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="DLWGQZ_kurzusfelvetel1.xsd"/>

<DLWGQZ_kurzusfelvetel>
    <kurzusfelvetel>
        <hallgato>
            <hnev>Szkárosi Szilárd</hnev>
            <szulev>2001-10-20</szulev>
            <szak evf="5">Mérnökinformatikus</szak>
        </hallgato>
        <kurzusok>
            <kurzus id="GEIAL332-B" jovahagyas="igen">
                <kurzusnev>Adatkezelés XML-ben</kurzusnev>
                <kredit>5</kredit>
                <hely>XXXII.</hely>
                <idopont>Kedd 12:00-14:00</idopont>
                <oktato>Dr. Bednarik László</oktato>
            </kurzus>
            <kurzus id="MIGEBANNY1" nyelv="angol">
                <kurzusnev>Angol nyelv nyelvvizsga előkészítő szint 1.</kurzusnev>
                <kredit>0</kredit>
                <hely>A5/202.</hely>
                <idopont>Hétfő 12:00-14:00</idopont>
                <oktato>Pásztor Krisztina Mária</oktato>
                <oraado>Pásztor Krisztina Mária</oraado>
            </kurzus>
            <kurzus id="GEIAL331-B" jovahagyas="igen">
                <kurzusnev>Web technológiák 1</kurzusnev>
                <kredit>5</kredit>
                <hely>A5/305.</hely>
                <idopont>Hétfő 14:00-16:00</idopont>
                <oktato>Agárdi Anita</oktato>
                <oraado>Pásztor Krisztina Mária</oraado>
            </kurzus>
            <kurzus id="GEFIT012-B">
                <kurzusnev>Fizika II.</kurzusnev>
                <kredit>4</kredit>
                <hely>A1/12.</hely>
                <idopont>Hétfő 10:00-12:00</idopont>
                <oktato>Dr. Pszota Gábor</oktato>
                <oraado>Nagy Ádám</oraado>
            </kurzus>                                 
        </kurzusok>
    </kurzusfelvetel>
</DLWGQZ_kurzusfelvetel>
